### ISSUE TITLE
1.9 version throws error looking for chai in dev mode

### ISSUE THREAD

**Issue by nate-strauser** [superstringsoftware/observatory#10]
on latest atmosphere version, when in dev mode i get this

`[6/2/2013][21:8:47.114][SERVER][][ERROR] Cannot find module 'chai'`

i got hit by a similar issue in the bundled version right after 1.9 was released, guessing maybe you missed a spot
## 

i even have chai installed globally via npm, doesnt seem to help

if i downgrade to 1.8, this error goes away

**Comment by jhoxray** [comment]
I believe this may be an issue with Chai install - I never made the require work with a global install for some reason. If you install Chai locally it should go away - if you could try and let me know if it solves it I'd appreciate as then we can localize the issue and work on fixing.

1.8 does not have the Testing part so there's no Chai that's why no error. In any case, it only affects your server testing functionality which is pre-alpha at this stage.

**Comment by Sivli-Embir** [comment]
Same issue for me:

`[12/2/2013][2:51:35.131][SERVER][][ERROR] Cannot find module 'chai'`

I haven't messed with tests in meteor so I can't offer suggestions quite yet.

**Comment by jhoxray** [comment]
Moved testing to a separate package.
