### ISSUE TITLE
Log information in the database WITHOUT publishing it to the clients

### ISSUE THREAD

**Issue by dgrabla** [superstringsoftware/observatory#21]
I want to be able to log something in the server and store it in the mongodb collection without this information streaming to the clients. You can setup if the log is displayed or not in the console, but the log is always streamed to the client via DDP in the _observatory_logs collection.

Is there a way to stop the streaming of new logs to the clients?

**Comment by ndhoule** [comment]
I'm also curious about this. It seems a bit insecure to me to publish all logs by default.

Any chance you found an answer to this, @dgrabla?

**Comment by dgrabla** [comment]
I didn't try to hack into observatory yet but I'm thinking I will detect the app is running in production and if so, override observatory's functions with a filesystem logger running in a fiber in the server and a mock function that does nothing in the client. Will this work for you as well?

**Comment by jperl** [comment]
I am looking into creating a hook for this and I am taking suggestions.

**Comment by jperl** [comment]
Initially I was going to setup a should_publish parameter under the `TLog` [constructor](https://github.com/superstringsoftware/observatory-apollo/blob/b754bb265ef3df07a406f2b342a169e951e6caee/TLog.coffee#L69) which would be a function hook that could return true of false. 

Although now I am thinking about using a global variable because we do not control [this](https://github.com/jhoxray/observatory/blob/125e3dc836064b7a55903f33e72c19131071da24/mars/observatoryTemplates.coffee#L1) `TLog.getLogger()`.

**Comment by jhoxray** [comment]
Merged @jperl's pull request, so now you can flexibly configure this. Thanks Jonathan!
